application: fastexto
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /bootstrap
  static_dir: bootstrap
- url: /css
  static_dir: css
- url: /.*
  script: fastexto.app
  
libraries:
- name: jinja2
  version: latest